### PR TITLE
Fix bug on SponsorModal.vue

### PR DESCRIPTION
**Pull request by iamonuwa**
@farahbrunache 
1. Fix overlay bug on SponsorModal.vue
2. Remove duplicate isLoading boolean data type

### CODE REVIEW

**Comment by farahbrunache** [comment]
@iamonuwa, after getting the changes it still doesn't work for me.

**Comment by iamonuwa** [comment]
Can you point out what is expected. I'll fix it immediately?

**Comment by farahbrunache** [comment]
@iamonuwa, please see this screencast: https://drive.google.com/file/d/1d0hRk_N1jVn13AzUsAQmyn9PkYTDYrLp/view?usp=sharing, the loading overlay is underneath the modal. The suggested changes don't change this behavior.

**Comment by iamonuwa** [comment]
Please approve my request.

**Comment by farahbrunache** [comment]
I will review this today.

**Comment by iamonuwa** [comment]
Awesome

**Comment by farahbrunache** [comment]
@iamonuwa, still don't see the updates. Closing this pull request.

**Pull request closed without merging**
