### PR TITLE
Feature: Screen overlay when a transaction is processing

### LINKED ISSUE #15: Feature: Screen overlay when a transaction is processing
**Feature: Screen overlay when a transaction is processing**

There are 10 blockchain functions in the app as seen below.

For each of the below there needs to be a screen overlay after the user clicks the button, so they are aware that something is happening and so they don't leave the page and press the below buttons multiple times.

createJob
cancelJob
claimJob
markJobComplete
setEvaluator
evaluateJobAsCompletedSucessfully
payoutJob
claimPayout
tip
sponsor

**Describe the solution you'd like**
While blockchain transactions are processing there needs to be a screen overlay on the page to indicate to the user that the app is working and to wait patiently. For example: https://www.behance.net/gallery/23015991/Freebie-Progress-Bar. Please choose a design and implement in each button.

**Definition of Done**
[ ] Please present the design suggestion in the discussion thread before full implementation

[ ] Each of the 10 buttons above have a screen overlay that is fired when a button is clicked. When the entire function is finished (both the blockchain portion and the remaining firebase calls) the overlay closes.

[ ] The implementation of the overlay has a "programmable" and "cancelable" option. For example: https://jsfiddle.net/ankurk91/w8y8k5wo. This is for future flexibility only. The final deliverable should have all overlays implemented as "programmable" and the user cannot escape the screen.

**Additional context**
Please only work from the `dev` branch.

### PR DESCRIPTION
**Pull request by iamonuwa**
@farahbrunache please review

Fixes #15

### CODE REVIEW

**Comment by farahbrunache** [comment]
@iamonuwa, I am checking now. Will confirm later today.

**Comment by iamonuwa** [comment]
Great! Hoping to hear from you soon.

**Comment by farahbrunache** [comment]
@iamonuwa, I found two minor issues. I made a lot of changes to your branch. Moving forward I won't do that because it can be confusing. I will push my changes.I need to make them to test the work you did. Basically some of the functions needed updated.

**Comment by iamonuwa** [comment]
Great! I'll make changes when you are ready :100:

**Pull request merged**
